name: Run and Test Docker Image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  run-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image from registry
        run: docker pull sambandh/cicd_assignment:v1

      - name: Run and Test Docker container
        run: |
          OUTPUT=$(docker run sambandh/cicd_assignment:v1)
          echo "Score = $OUTPUT"
          if [[ $(echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}') == 1 ]]; then
            echo "FAILED : Score is less than 0.50"
            exit 1
          else
            echo "PASSED : Score is greater than 0.50"
          fi        
