name: Check Minimum Score

on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

permissions:
  contents: read

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create model
        run:
          python train.py

      - name: Test model
        run: |
          OUTPUT=$(python test.py)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t HematoDiagnoser:latest .
      
      - name: Push Docker Image
        run: docker push HematoDiagnoser:latest
    
  pull-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull HematoDiagnoser:latest

    - name: Run Docker Image
      run: docker run HematoDiagnoser:latest

    - name: Check Score
      run: |
        # Run the docker image and evaluate if threshold is met
        score=$(docker run HematoDiagnoser:latest)
        if (( $(echo "$score > 0.50" | bc -l) )); then
          echo "Score is greater than 0.50"
          exit 0
        else
          echo "Score is not greater than 0.50"
          exit 1
        fi

